language: node_js
# node_js:
# - node
deploy:
  provider: s3
  access_key_id: AKIAJF4C3YFY2VOJJSIA
  secret_access_key:
    secure: S8psIsxRH7gaMiBXD2Gqix0PgzwOZThMwteZL+oiSJMmuUdlKQw5kgAzKOMRxds1Bh4W/8I2f9fFa91OaC50O5mry9y8fI5ExpBkEN/hntzQQiSZqsh0ANf9p9iN0tjaiIhCLRQqgWMDlGVTwIaDWdf3zyWlXNkqFpIvOn4xH41l4Uep3JEysOfRBcJTjTaZGF0y0OOVKWedC99E0xe3Z3kyXqzFzFaFjc1IzkGz5pCcVHrJ3hwd44qMG8GTjpqlHrB4Z+89ScJYPUNN2DgcqVPRHNojzhi1dbprrrgXjqQSGnoRLnAwYGT8CmW7E6xh/0ALQjYqqGoptCJ2qhqC3bENl7qKsreh5jbCg4AgoSL9oOIuyIV8zCbpGZNGyyL++vpapnbLTr87v+Q2FyN5sRSfjH/qI4Tvso8tRoYppHP/bmnHuuGPUcLuX6uRzuDTo7Rp5VKCK2pMcMoRoL/t+K/Sa0d1X7yFIf9M9MlfW57aoRfgslu4LvTg0Nsv6b9QlhV3fOm+y+n1qQQRUaMQqnt4WZKu1CHICnOZGs0SShh3mHnmV69lC6F/FKiMhRJ9kr3QsqCrT2uLj0/OmI1sRVaRo1en6firTYMYBb4UOLvz2HHil1js+enTYVNFtYjBq3lsPG/lEWVudOJdlysLE/F0I0b6nwfg0F8rMguhkuA=
  bucket: vitalpixel.org
  acl: public_read
  local_dir: deploy
  on:
    repo: vitalPixel/vitalpixel.org-v2
