language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAJF4C3YFY2VOJJSIA
  secret_access_key:
    secure: "wDrpyiH0Hgu++ZNgOjhvVbXo7RPHNin/gRGWLPEw/V4VedmvgwnDwVQfq4Rz4GeFi9IP2Va6MBOZOB9zS4nFewwYaMpueFwU6lHTtXsbOI9d+y18JNPE0LPmRqp3tBDekLpD6t36HzIiqrddAzW9fil43as1KOgt0Xv99bsE+IXne+Md+mByep97P2zbHh30p5EOzcArjKmHxKTkvN1lYzWMB5qQ7RtW4McnS39WF9cqySU0JjZDb0iQK0H0ahRNMEsPPAUbex/VHh756Y8MnTAFMYe042OdtXwKkM9j4p5MBUi68WDiqQEV/3Fr32ggME1MX4raHjOnGXahMqWc9s6Lkktr7RKxcwvK3DrgwgUjMXPOKVOrumKj+wmDWCeGWhNOAvBipCJzlfbEl/NvGmhab1V0Dmav6vugJ6w/vzzM9TpJ9G0MAhWB+Nyk/OYl35cIEPuvoMLpAiXyqdG0M+GCo43rHlSgxlp4sbhO/dol8JWsfBXMKdKyfVCoIE7hoKNz6vGs0cEreY+KaqUvzDdcNj67t6cXnOk1K3Fp1RONRoGAnY4syGjLsX8wFjaWCip8JPVz9mpKrwr0SgJ/BM1dEffZkOLMCb5oWWae/SFlyOvShXKlXEunABth4QLOsV1X/KzVbH4sjwaoSdWhh+icBT2caEUXdhw8RRRVmCk="
  bucket: vitalpixel.org
  acl: public_read
